@startuml
participant Actor
Actor -> Player : fight
activate Player
Player -> Console : afficheln
activate Console
Console -> Console : affiche
activate Console
Console -> Interaction : pause
activate Interaction
Interaction --> Console
deactivate Interaction
Console --> Console
deactivate Console
Console --> Player
deactivate Console
Player -> Player : fleeTheFight
activate Player
Player -> Console : afficheInLine
activate Console
Console --> Player
deactivate Console
Player -> Interaction : lireString
activate Interaction
Interaction --> Player
deactivate Interaction
Player --> Player
deactivate Player
Player -> Enemy : inLife
activate Enemy
Enemy --> Player
deactivate Enemy
Player -> Console : affiche
activate Console
Console -> Interaction : pause
activate Interaction
Interaction --> Console
deactivate Interaction
Console --> Player
deactivate Console
Player -> Console : affiche
activate Console
Console -> Interaction : pause
activate Interaction
Interaction --> Console
deactivate Interaction
Console --> Player
deactivate Console
Player -> Enemy : removeLifePoint
activate Enemy
Enemy -> Enemy : inLife
activate Enemy
Enemy --> Enemy
deactivate Enemy
Enemy --> Player
deactivate Enemy
Player -> Console : afficheln
activate Console
Console -> Console : affiche
activate Console
Console -> Interaction : pause
activate Interaction
Interaction --> Console
deactivate Interaction
Console --> Console
deactivate Console
Console --> Player
deactivate Console
Player -> Game : looseGame
activate Game
Game -> Console : afficheln
activate Console
Console -> Console : affiche
activate Console
Console -> Interaction : pause
activate Interaction
Interaction --> Console
deactivate Interaction
Console --> Console
deactivate Console
Console --> Game
deactivate Console
Game -> Console : afficheln
activate Console
Console -> Console : affiche
activate Console
Console -> Interaction : pause
activate Interaction
Interaction --> Console
deactivate Interaction
Console --> Console
deactivate Console
Console --> Game
deactivate Console
Game --> Player
deactivate Game
Player -> ClassicMethods : random
activate ClassicMethods
ClassicMethods --> Player
deactivate ClassicMethods
Player -> Console : affiche
activate Console
Console -> Interaction : pause
activate Interaction
Interaction --> Console
deactivate Interaction
Console --> Player
deactivate Console
Player -> Console : afficheln
activate Console
Console -> Console : affiche
activate Console
Console -> Interaction : pause
activate Interaction
Interaction --> Console
deactivate Interaction
Console --> Console
deactivate Console
Console --> Player
deactivate Console
Player -> Room : clearEnemy
activate Room
Room --> Player
deactivate Room
return
@enduml